import { Plant } from './types';

export const PLANT_DATA: Plant[] = [
  {
    id: 1,
    name: 'Aglaonema',
    imageUrl: 'https://picsum.photos/seed/Aglaonema/400/300',
    environment: 'Thrives in warm, humid indoor spaces; avoid cold drafts and sudden temp changes.',
    water: 'Keep soil consistently moist but not soggy; reduce in winter.',
    sunlight: 'Low to bright indirect light; avoid direct sun.',
    soil: 'Rich, well-draining potting mix.',
    benefits: 'Powerful air purifier; easy-care with attractive foliage.',
  },
  {
    id: 2,
    name: 'Cactus',
    imageUrl: 'https://picsum.photos/seed/Cactus/400/300',
    environment: 'Perfect for arid, low-humidity homes and sun-filled windowsills.',
    water: 'Water every 10–14 days, or less in winter; allow soil to dry out.',
    sunlight: 'Loves at least 4–6 hours of direct sunlight daily.',
    soil: 'Gritty, sandy, quick-draining cactus/succulent soil.',
    benefits: 'Extremely low-maintenance; adds architectural flair and purifies air.',
  },
  {
    id: 3,
    name: 'Echeveria',
    imageUrl: 'https://picsum.photos/seed/Echeveria/400/300',
    environment: 'Needs dry, airy indoor locations; best away from constant humidity.',
    water: 'Every 1–2 weeks; avoid getting water in the rosette.',
    sunlight: 'Bright indirect to partial sun; vibrant color in strong light.',
    soil: 'Well-draining succulent mix.',
    benefits: 'Ornamental rosettes; easy for beginners.',
  },
  {
    id: 4,
    name: 'Jade Plant',
    imageUrl: 'https://picsum.photos/seed/JadePlant/400/300',
    environment: 'Warm, dry rooms; keep away from cold drafts.',
    water: 'Every 2–3 weeks; drier in winter; let soil dry between waterings.',
    sunlight: 'Bright indirect light preferred.',
    soil: 'Succulent or cactus potting mix.',
    benefits: 'Said to bring prosperity; air purifying and easy to propagate.',
  },
  {
    id: 5,
    name: 'Lavender',
    imageUrl: 'https://picsum.photos/seed/Lavender/400/300',
    environment: 'Bright, ventilated spots; ideally a sunny window with dry air.',
    water: 'Water when topsoil dries; prefers to be a bit dry over wet.',
    sunlight: 'Minimum 6–8 hours of full sun.',
    soil: 'Slightly alkaline, fast-draining soil; likes sand or gravel mixed in.',
    benefits: 'Calming scent; deters pests; used in essential oils and aromatherapy.',
  },
  {
    id: 6,
    name: 'Money Plant (Pothos)',
    imageUrl: 'https://picsum.photos/seed/Pothos/400/300',
    environment: 'Adaptable to most indoor conditions, even low-light rooms.',
    water: 'Once top inch dries; more tolerant of underwatering than overwatering.',
    sunlight: 'Low to moderate indirect light; will grow in fluorescent office lighting.',
    soil: 'Loose, fast-draining potting soil.',
    benefits: 'Powerful air purifier; said to bring good fortune; fastest-growing vine for greening spaces.',
  },
  {
    id: 7,
    name: 'Snake Plant',
    imageUrl: 'https://picsum.photos/seed/SnakePlant/400/300',
    environment: 'Thrives in nearly any indoor spot; highly resilient.',
    water: 'Allow top inch of soil to dry before watering; very drought tolerant.',
    sunlight: 'Handles low light but prefers indirect light.',
    soil: 'Loose, well-draining soil.',
    benefits: 'NASA-rated air purifier, nearly impossible to kill, ideal for bedrooms/offices.',
  },
  {
    id: 8,
    name: 'ZZ Plant',
    imageUrl: 'https://picsum.photos/seed/ZZPlant/400/300',
    environment: 'Adaptable to any room, even those with low light or poor airflow.',
    water: 'Every 2–3 weeks; let soil fully dry between waterings.',
    sunlight: 'Tolerates low to medium light; don’t place in full, harsh sun.',
    soil: 'Well-draining soil mix, such as aroid blend or cactus mix.',
    benefits: 'One of the most tolerant houseplants; air purifier and extremely low maintenance.',
  },
  {
    id: 9,
    name: 'Fiddle Leaf Fig',
    imageUrl: 'https://picsum.photos/seed/FiddleFig/400/300',
    environment: 'Needs a stable, bright spot away from drafts. Can be dramatic but rewarding.',
    water: 'Water when the top inch of soil is dry. Avoid overwatering.',
    sunlight: 'Bright, indirect light is crucial. Avoid direct sun which can scorch leaves.',
    soil: 'Well-draining, nutrient-rich potting mix.',
    benefits: 'A stylish, statement plant that adds a touch of the tropics to any room.',
  },
  {
    id: 10,
    name: 'Peace Lily',
    imageUrl: 'https://picsum.photos/seed/PeaceLily/400/300',
    environment: 'Prefers consistent temperatures and appreciates higher humidity.',
    water: 'Keep soil consistently moist. It will droop dramatically when thirsty.',
    sunlight: 'Thrives in medium to low indirect light. Can tolerate fluorescent lights.',
    soil: 'Moisture-retaining but well-draining potting soil.',
    benefits: 'Excellent air purifier and produces elegant white flowers.',
  },
  {
    id: 11,
    name: 'Spider Plant',
    imageUrl: 'https://picsum.photos/seed/SpiderPlant/400/300',
    environment: 'Very adaptable and resilient, making it great for beginners.',
    water: 'Water thoroughly, but allow soil to dry out between waterings.',
    sunlight: 'Prefers bright, indirect light but can tolerate lower light conditions.',
    soil: 'Any well-draining potting mix.',
    benefits: 'Produces "spiderettes" which are easy to propagate. A great air purifier.',
  },
  {
    id: 12,
    name: 'Rubber Plant',
    imageUrl: 'https://picsum.photos/seed/RubberPlant/400/300',
    environment: 'Likes a consistent environment without too many changes in light or temperature.',
    water: 'Water when the top inch of soil is dry. More tolerant of underwatering than overwatering.',
    sunlight: 'Needs bright, indirect light. Not enough light will cause leggy growth.',
    soil: 'Well-aerated and well-draining potting soil.',
    benefits: 'Features large, glossy leaves that make a bold statement.',
  },
  {
    id: 13,
    name: 'Calathea',
    imageUrl: 'https://picsum.photos/seed/Calathea/400/300',
    environment: 'Loves high humidity, making it perfect for bathrooms or kitchens.',
    water: 'Keep the soil consistently moist but not waterlogged. Use filtered water if possible.',
    sunlight: 'Bright, indirect light is best. Direct sun will fade the vibrant leaf patterns.',
    soil: 'A peat-based potting mix that retains moisture well.',
    benefits: 'Known as "prayer plants" because their leaves fold up at night. Stunning foliage.',
  },
];